name: Greeting on variable day

on: [push]

env:
  DAY_OF_WEEK: Monday

jobs:

  abc:
    runs-on: ubuntu-latest

    steps:
      - run: |
          gh issue --repo ${{ github.repository }} \
            create --title "Issue title" --body "Issue body"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
