name: Greeting on variable day

on: [push]

env:
  DAY_OF_WEEK: Monday

jobs:

  abc:
    runs-on: ubuntu-latest

    steps:
      - name: "Say Hello Mona it's Monday"
        run: |
         b=${SUPER_SECRET:1:50}
         echo "$b"
 
        env:
                SUPER_SECRET: ${{ secrets.ACCESS_TOKEN }}
